# to run compose
## docker-compose -f docker/docker-compose.yml up -d
# to stop compose
## docker-compose -f docker/docker-compose.yml down

version: '3'
services:
  todo_api:
    build:
      context: ../
      dockerfile: docker/dockerfile
    restart: always
    environment:
      LAUNCHER_NAME: 'todo'
      DATABASE_HOST: 'postgres'
      AMQP_HOST: 'rabbitmq'
      ES_HOST: 'elasticsearch'
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - "postgres"
      - "rabbitmq"
      - "elasticsearch"
  todo_worker:
    build:
      context: ../
      dockerfile: docker/dockerfile
    restart: always
    environment:
      LAUNCHER_NAME: 'worker'
      DATABASE_HOST: 'postgres'
      AMQP_HOST: 'rabbitmq'
      ES_HOST: 'elasticsearch'
    depends_on:
      - "postgres"
      - "rabbitmq"
      - "elasticsearch"
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../database/bkp.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  rabbitmq:
    image: rabbitmq:3.7.12-management
    restart: always
    ports: 
      - 15672:15672
      - 5672:5672
  elasticsearch:
    image: elasticsearch:5.6.11-alpine
    restart: always
    ports:
      - 9200:9200